namespace TexasList.Data.Migrations
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Migrations;
    using System.Linq;
    using TexasList.Data.Models;

    internal sealed class Configuration : DbMigrationsConfiguration<TexasList.Data.TexasListContext>
    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
        }

        protected override void Seed(TexasList.Data.TexasListContext context)
        {

            context.Users.AddOrUpdate(
                  u => u.UserId,
                  new User { UserName = "SusieQ", Email = "sue@gmail.com" },
                  new User { UserName = "Bobby", Email = "bob@yahoo.com" },
                  new User { UserName = "Eric Rocks", Email = "rockon@gmail.com" },
                  new User { UserName = "Nunya", Email = "nunyabiz@gmail.com" },
                  new User { UserName = "Steve", Email = "steve@gmail.com" },
                  new User { UserName = "William the Great", Email = "billy@gmail.com" },
                  new User { UserName = "Sarah Smart", Email = "smartypants@gmail.com" },
                  new User { UserName = "Glenn", Email = "gman@gmail.com" },
                  new User { UserName = "Hiya", Email = "hello@gmail.com" },
                  new User { UserName = "Wendy", Email = "frosty@gmail.com" }

            );

            context.SaveChanges();
            context.Cities.AddOrUpdate(
                  c => c.CityId,
                  new City { CityName = "Austin" },
                  new City { CityName = "Dallas / Ft.Worth" },
                  new City { CityName = "Houston" },
                  new City { CityName = "San Antonio" }

                );

            context.SaveChanges();
            context.Categories.AddOrUpdate(
                  a => a.CategoryId,
                  new Category { CategoryName = "Events" },
                  new Category { CategoryName = "Real Estate" },
                  new Category { CategoryName = "Personals" },
                  new Category { CategoryName = "Jobs" },
                  new Category { CategoryName = "Stuff for Sale" },
                  new Category { CategoryName = "Local Services" }
               );

            context.SaveChanges();
            context.Subcategories.AddOrUpdate(
                s => s.SubcategoryName,
                new Subcategory { SubcategoryName = "Concerts", CategoryId = 1 },
                new Subcategory { SubcategoryName = "Sports", CategoryId = 1 },
                new Subcategory { SubcategoryName = "Family Friendly", CategoryId = 1 },
                new Subcategory { SubcategoryName = "Charities and Causes", CategoryId = 1 },
                new Subcategory { SubcategoryName = "Misc. Events", CategoryId = 1 },

                new Subcategory { SubcategoryName = "Residential For Rent", CategoryId = 2 },
                new Subcategory { SubcategoryName = "Residential For Sale", CategoryId = 2 },
                new Subcategory { SubcategoryName = "Commercial For Rent", CategoryId = 2 },
                new Subcategory { SubcategoryName = "Commercial For Sale", CategoryId = 2 },
                new Subcategory { SubcategoryName = "Misc. Real Estate", CategoryId = 2 },

                new Subcategory { SubcategoryName = "Boy meets Girl", CategoryId = 3 },
                new Subcategory { SubcategoryName = "Boy meets Boy", CategoryId = 3 },
                new Subcategory { SubcategoryName = "Girl meets Girl", CategoryId = 3 },
                new Subcategory { SubcategoryName = "Farmers Only", CategoryId = 3 },
                new Subcategory { SubcategoryName = "Misc. Personals", CategoryId = 3 },

                new Subcategory { SubcategoryName = "Accounting / Finance", CategoryId = 4 },
                new Subcategory { SubcategoryName = "Computers / Tech / Engineering", CategoryId = 4 },
                new Subcategory { SubcategoryName = "Education / Childcare", CategoryId = 4 },
                new Subcategory { SubcategoryName = "Legal", CategoryId = 4 },
                new Subcategory { SubcategoryName = "Manufacturing / Labor", CategoryId = 4 },
                new Subcategory { SubcategoryName = "Office Staff", CategoryId = 4 },
                new Subcategory { SubcategoryName = "Restaurant / Bar Staff", CategoryId = 4 },
                new Subcategory { SubcategoryName = "Sales / Retail", CategoryId = 4 },
                new Subcategory { SubcategoryName = "Misc. Jobs", CategoryId = 4 },

                new Subcategory { SubcategoryName = "Animals", CategoryId = 5 },
                new Subcategory { SubcategoryName = "Antiques", CategoryId = 5 },
                new Subcategory { SubcategoryName = "Books", CategoryId = 5 },
                new Subcategory { SubcategoryName = "Children's Stuff", CategoryId = 5 },
                new Subcategory { SubcategoryName = "Electronics", CategoryId = 5 },
                new Subcategory { SubcategoryName = "For Free", CategoryId = 5 },
                new Subcategory { SubcategoryName = "Furniture", CategoryId = 5 },
                new Subcategory { SubcategoryName = "General Houshold", CategoryId = 5 },
                new Subcategory { SubcategoryName = "Jewelry", CategoryId = 5 },
                new Subcategory { SubcategoryName = "Vehicles", CategoryId = 5 },
                new Subcategory { SubcategoryName = "Misc. for Sale", CategoryId = 5 },

                new Subcategory { SubcategoryName = "Childcare", CategoryId = 6 },
                new Subcategory { SubcategoryName = "Delivery and Moving", CategoryId = 6 },
                new Subcategory { SubcategoryName = "Electrical / Plumbing / HVAC", CategoryId = 6 },
                new Subcategory { SubcategoryName = "Home Repair and Improvement", CategoryId = 6 },
                new Subcategory { SubcategoryName = "Landscaping", CategoryId = 6 },
                new Subcategory { SubcategoryName = "Mechanics", CategoryId = 6 },
                new Subcategory { SubcategoryName = "Misc. Services", CategoryId = 6 }

                );

            context.SaveChanges();
            context.Posts.AddOrUpdate(
           p => p.PostId,
           new Post { Title = "Couch for Sale", Amount = "100.25", UserId = 1, CategoryId = 5, CityId = 1, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Bike for Sale", Amount = "50.00", UserId = 2, CategoryId = 5, CityId = 1, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Room for Rent", Amount = "425.00", UserId = 3, CategoryId = 2, CityId = 1, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Office Building for Sale", Amount = "450,000.00", UserId = 4, CategoryId = 2, CityId = 1, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Office for Rent", Amount = "1200.00", UserId = 4, CategoryId = 2, CityId = 1, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Free TV", Amount = "0", UserId = 5, CategoryId = 5, CityId = 1, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Need a CPA", Amount = "42,000/yr", UserId = 6, CategoryId = 4, CityId = 1, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Bartender", Amount = "8.25/ hr", UserId = 6, CategoryId = 4, CityId = 1, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Paralegal", Amount = "32,000/ yr doe", UserId = 7, CategoryId = 4, CityId = 1, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Outside Sales", Amount = "14/hr", UserId = 5, CategoryId = 4, CityId = 1, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Need a Plumber?", Amount = "0", UserId = 1, CategoryId = 6, CityId = 1, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Looking for the One", Amount = " 0", UserId = 1, CategoryId = 3, CityId = 1, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Wokin por numb", Amount = "0", UserId = 8, CategoryId = 2, CityId = 1, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "One Lemon of a car", Amount = "500", UserId = 9, CategoryId = 5, CityId = 1, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "ipsum dolor sit amet", Amount = "100.25", UserId = 1, CategoryId = 5, CityId = 1, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "ipsum dolor sit amet", Amount = "50.00", UserId = 2, CategoryId = 5, CityId = 1, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "ipsum dolor sit amet", Amount = "425.00", UserId = 3, CategoryId = 2, CityId = 1, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "ipsum dolor sit amet", Amount = "450,000.00", UserId = 4, CategoryId = 2, CityId = 1, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Offipsum dolor sit amet", Amount = "1200.00", UserId = 4, CategoryId = 2, CityId = 1, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Freipsum dolor sit ametV", Amount = "0", UserId = 5, CategoryId = 5, CityId = 1, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Neipsum dolor sit ametPA", Amount = "42000", UserId = 6, CategoryId = 4, CityId = 1, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Baipsum dolor sit ameter", Amount = "8.25", UserId = 6, CategoryId = 4, CityId = 1, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Paipsum dolor sit ametl", Amount = "32000", UserId = 7, CategoryId = 4, CityId = 1, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Outipsum dolor sit ametles", Amount = "14", UserId = 5, CategoryId = 4, CityId = 1, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Neeipsum dolor sit ametmber?", Amount = "0", UserId = 1, CategoryId = 6, CityId = 1, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Looipsum dolor sit amethe One", Amount = "0", UserId = 1, CategoryId = 3, CityId = 1, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Wokipsum dolor sit ametumb", Amount = "0", UserId = 8, CategoryId = 2, CityId = 1, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Onipsum dolor sit ameta car", Amount = "500", UserId = 9, CategoryId = 5, CityId = 1, AdBody = "Lor em ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Couch for Sale", Amount = "100.25", UserId = 1, CategoryId = 5, CityId = 2, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Bike for Sale", Amount = "50.00", UserId = 2, CategoryId = 5, CityId = 2, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Room for Rent", Amount = "425.00", UserId = 3, CategoryId = 2, CityId = 2, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Office Building for Sale", Amount = "450000.00", UserId = 4, CategoryId = 2, CityId = 2, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Office for Rent", Amount = "1200.00", UserId = 4, CategoryId = 2, CityId = 2, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Free TV", Amount = "0", UserId = 5, CategoryId = 5, CityId = 2, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Need a CPA", Amount = "42000", UserId = 6, CategoryId = 4, CityId = 2, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Bartender", Amount = "8.25", UserId = 6, CategoryId = 4, CityId = 2, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Paralegal", Amount = "32000", UserId = 7, CategoryId = 4, CityId = 2, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Outside Sales", Amount = "14", UserId = 5, CategoryId = 4, CityId = 2, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Need a Plumber?", Amount = "0", UserId = 1, CategoryId = 6, CityId = 2, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Looking for the One", Amount = "0", UserId = 1, CategoryId = 3, CityId = 2, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Wokin por numb", Amount = "0", UserId = 8, CategoryId = 2, CityId = 2, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "One Lemon of a car", Amount = "500", UserId = 9, CategoryId = 5, CityId = 2, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "ipsum dolor sit amet", Amount = "100.25", UserId = 1, CategoryId = 5, CityId = 2, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "ipsum dolor sit amet", Amount = "50.00", UserId = 2, CategoryId = 5, CityId = 2, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "ipsum dolor sit amet", Amount = "425.00", UserId = 3, CategoryId = 2, CityId = 2, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "ipsum dolor sit amet", Amount = "450000.00", UserId = 4, CategoryId = 2, CityId = 2, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Offipsum dolor sit amet", Amount = "1200.00", UserId = 4, CategoryId = 2, CityId = 2, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Freipsum dolor sit ametV", Amount = "0", UserId = 5, CategoryId = 5, CityId = 2, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Neipsum dolor sit ametPA", Amount = "42000", UserId = 6, CategoryId = 4, CityId = 2, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Baipsum dolor sit ameter", Amount = "8.25", UserId = 6, CategoryId = 4, CityId = 2, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Paipsum dolor sit ametl", Amount = "32000", UserId = 7, CategoryId = 4, CityId = 2, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Outipsum dolor sit ametles", Amount = "14", UserId = 5, CategoryId = 4, CityId = 2, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Neeipsum dolor sit ametmber?", Amount = "0", UserId = 1, CategoryId = 6, CityId = 2, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Looipsum dolor sit amethe One", Amount = "0", UserId = 1, CategoryId = 3, CityId = 2, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Wokipsum dolor sit ametumb", Amount = "0", UserId = 8, CategoryId = 2, CityId = 2, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Onipsum dolor sit ameta car", Amount = "500", UserId = 9, CategoryId = 5, CityId = 2, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Couch for Sale", Amount = "100.25", UserId = 1, CategoryId = 5, CityId = 3, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Bike for Sale", Amount = "50.00", UserId = 2, CategoryId = 5, CityId = 3, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Room for Rent", Amount = "425.00", UserId = 3, CategoryId = 2, CityId = 3, AdBody = "Lo rem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Office Building for Sale", Amount = "450000.00", UserId = 4, CategoryId = 2, CityId = 3, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Office for Rent", Amount = "1200.00", UserId = 4, CategoryId = 2, CityId = 3, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Free TV", Amount = "0", UserId = 5, CategoryId = 5, CityId = 3, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Need a CPA", Amount = "42000", UserId = 6, CategoryId = 4, CityId = 3, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Bartender", Amount = "8.25", UserId = 6, CategoryId = 4, CityId = 3, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Paralegal", Amount = "32000", UserId = 7, CategoryId = 4, CityId = 3, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Outside Sales", Amount = "14", UserId = 5, CategoryId = 4, CityId = 3, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Need a Plumber?", Amount = "0", UserId = 1, CategoryId = 6, CityId = 3, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Looking for the One", Amount = "0", UserId = 1, CategoryId = 3, CityId = 3, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Wokin por numb", Amount = "0", UserId = 8, CategoryId = 2, CityId = 3, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "One Lemon of a car", Amount = "500", UserId = 9, CategoryId = 5, CityId = 3, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "ipsum dolor sit amet", Amount = "100.25", UserId = 1, CategoryId = 5, CityId = 3, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "ipsum dolor sit amet", Amount = "50.00", UserId = 2, CategoryId = 5, CityId = 3, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "ipsum dolor sit amet", Amount = "425.00", UserId = 3, CategoryId = 2, CityId = 3, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "ipsum dolor sit amet", Amount = "450000.00", UserId = 4, CategoryId = 2, CityId = 3, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Offipsum dolor sit amet", Amount = "1200.00", UserId = 4, CategoryId = 2, CityId = 3, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Freipsum dolor sit ametV", Amount = "0", UserId = 5, CategoryId = 5, CityId = 3, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Neipsum dolor sit ametPA", Amount = "42000", UserId = 6, CategoryId = 4, CityId = 3, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Baipsum dolor sit ameter", Amount = "8.25", UserId = 6, CategoryId = 4, CityId = 3, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Paipsum dolor sit ametl", Amount = "32000", UserId = 7, CategoryId = 4, CityId = 3, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Outipsum dolor sit ametles", Amount = "14", UserId = 5, CategoryId = 4, CityId = 3, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Neeipsum dolor sit ametmber?", Amount = "0", UserId = 1, CategoryId = 6, CityId = 3, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Looipsum dolor sit amethe One", Amount = "0", UserId = 1, CategoryId = 3, CityId = 3, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Wokipsum dolor sit ametumb", Amount = "0", UserId = 8, CategoryId = 2, CityId = 3, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Onipsum dolor sit ameta car", Amount = "500", UserId = 9, CategoryId = 5, CityId = 3, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Couch for Sale", Amount = "100.25", UserId = 1, CategoryId = 5, CityId = 4, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Bike for Sale", Amount = "50.00", UserId = 2, CategoryId = 5, CityId = 4, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Room for Rent", Amount = "425.00", UserId = 3, CategoryId = 2, CityId = 4, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Office Building for Sale", Amount = "450000.00", UserId = 4, CategoryId = 2, CityId = 4, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Office for Rent", Amount = "1200.00", UserId = 4, CategoryId = 2, CityId = 4, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Free TV", Amount = "0", UserId = 5, CategoryId = 5, CityId = 4, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Need a CPA", Amount = "42000", UserId = 6, CategoryId = 4, CityId = 4, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Bartender", Amount = "8.25", UserId = 6, CategoryId = 4, CityId = 4, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Paralegal", Amount = "32000", UserId = 7, CategoryId = 4, CityId = 4, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Outside Sales", Amount = "14", UserId = 5, CategoryId = 4, CityId = 4, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Need a Plumber?", Amount = "0", UserId = 1, CategoryId = 6, CityId = 4, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Looking for the One", Amount = "0", UserId = 1, CategoryId = 3, CityId = 4, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Wokin por numb", Amount = "0", UserId = 8, CategoryId = 2, CityId = 4, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "One Lemon of a car", Amount = "500", UserId = 9, CategoryId = 5, CityId = 4, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "ipsum dolor sit amet", Amount = "100.25", UserId = 1, CategoryId = 5, CityId = 4, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "ipsum dolor sit amet", Amount = "50.00", UserId = 2, CategoryId = 5, CityId = 4, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "ipsum dolor sit amet", Amount = "425.00", UserId = 3, CategoryId = 2, CityId = 4, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "ipsum dolor sit amet", Amount = "450000.00", UserId = 4, CategoryId = 2, CityId = 4, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Offipsum dolor sit amet", Amount = "1200.00", UserId = 4, CategoryId = 2, CityId = 4, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Freipsum dolor sit ametV", Amount = "0", UserId = 5, CategoryId = 5, CityId = 4, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Neipsum dolor sit ametPA", Amount = "42000", UserId = 6, CategoryId = 4, CityId = 4, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Baipsum dolor sit ameter", Amount = "8.25", UserId = 6, CategoryId = 4, CityId = 4, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Paipsum dolor sit ametl", Amount = "32000", UserId = 7, CategoryId = 4, CityId = 4, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Outipsum dolor sit ametles", Amount = "14", UserId = 5, CategoryId = 4, CityId = 4, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Neeipsum dolor sit ametmber?", Amount = "0", UserId = 1, CategoryId = 6, CityId = 4, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Looipsum dolor sit amethe One", Amount = "0", UserId = 1, CategoryId = 3, CityId = 4, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Wokipsum dolor sit ametumb", Amount = "0", UserId = 8, CategoryId = 2, CityId = 4, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." },
           new Post { Title = "Onipsum dolor sit ameta car", Amount = "500", UserId = 9, CategoryId = 5, CityId = 4, AdBody = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat." }

          );

            context.SaveChanges();

            context.PostSubcategories.AddOrUpdate(
                p => p.PostSubcategoryId,
                new PostSubcategory { PostId=1,  SubcategoryId = 31},
                new PostSubcategory { PostId=2, SubcategoryId = 34},
                new PostSubcategory { PostId=2, SubcategoryId = 28},
                new PostSubcategory { PostId=3 , SubcategoryId = 6},
                new PostSubcategory { PostId=4, SubcategoryId = 9},
                new PostSubcategory { PostId= 5, SubcategoryId=8},
                new PostSubcategory { PostId=6, SubcategoryId = 30}, 
                new PostSubcategory { PostId=6, SubcategoryId = 29},
                new PostSubcategory { PostId=7, SubcategoryId = 16},
                new PostSubcategory { PostId=8, SubcategoryId = 22},
                new PostSubcategory { PostId=9, SubcategoryId =19}, 
                new PostSubcategory { PostId=9, SubcategoryId =21},
                new PostSubcategory { PostId=10, SubcategoryId =23},
                new PostSubcategory { PostId=11, SubcategoryId = 38},
                new PostSubcategory { PostId=12, SubcategoryId = 11},
                new PostSubcategory { PostId=12, SubcategoryId =14},
                new PostSubcategory { PostId= 13, SubcategoryId = 15},
                new PostSubcategory { PostId= 14, SubcategoryId = 34 },
                new PostSubcategory { PostId=15, SubcategoryId = 31 },
                new PostSubcategory { PostId=16, SubcategoryId = 34},
                new PostSubcategory { PostId=16, SubcategoryId = 28},
                new PostSubcategory { PostId=17, SubcategoryId = 6},
                new PostSubcategory { PostId=18, SubcategoryId = 9},
                new PostSubcategory { PostId=19, SubcategoryId = 8},
                new PostSubcategory { PostId=20, SubcategoryId = 30},
                new PostSubcategory { PostId=20, SubcategoryId = 29},
                new PostSubcategory { PostId=21, SubcategoryId = 16},
                new PostSubcategory { PostId=22, SubcategoryId = 22},
                new PostSubcategory { PostId=23, SubcategoryId =19},
                new PostSubcategory { PostId=23,  SubcategoryId =21},
                new PostSubcategory { PostId=24, SubcategoryId =23},
                new PostSubcategory { PostId=25, SubcategoryId = 38},
                new PostSubcategory { PostId= 26, SubcategoryId = 11},
                new PostSubcategory { PostId= 26,  SubcategoryId =14},
                new PostSubcategory { PostId=27, SubcategoryId = 15},
                new PostSubcategory { PostId=28, SubcategoryId = 34 },
                new PostSubcategory { PostId=29, SubcategoryId = 31 },
                new PostSubcategory { PostId=30, SubcategoryId = 34},
                new PostSubcategory { PostId=30,  SubcategoryId = 28},
                new PostSubcategory { PostId=31, SubcategoryId = 6},
                new PostSubcategory { PostId=32, SubcategoryId = 9},
                new PostSubcategory { PostId=33, SubcategoryId = 8},
                new PostSubcategory { PostId=34, SubcategoryId = 30 },
                new PostSubcategory { PostId=34, SubcategoryId = 29},
                new PostSubcategory { PostId=35, SubcategoryId = 16},
                new PostSubcategory { PostId=36, SubcategoryId = 22},
                new PostSubcategory { PostId=37, SubcategoryId =19},
                new PostSubcategory { PostId=37,  SubcategoryId =21},
                new PostSubcategory { PostId=38, SubcategoryId =23},
                new PostSubcategory { PostId=39, SubcategoryId = 38},
                new PostSubcategory { PostId=40, SubcategoryId = 11},
                new PostSubcategory { PostId=40,  SubcategoryId =14},
                new PostSubcategory { PostId=41, SubcategoryId = 15},
                new PostSubcategory { PostId=42, SubcategoryId = 34 },
                new PostSubcategory { PostId=43, SubcategoryId = 31 },
                new PostSubcategory { PostId=44, SubcategoryId = 34},
                new PostSubcategory { PostId=44, SubcategoryId = 28},
                new PostSubcategory { PostId=45, SubcategoryId = 6},
                new PostSubcategory { PostId=46, SubcategoryId = 9},
                new PostSubcategory { PostId=47, SubcategoryId = 8},
                new PostSubcategory { PostId=48, SubcategoryId = 30 },
                 new PostSubcategory { PostId=48, SubcategoryId = 29},
                new PostSubcategory { PostId=49, SubcategoryId = 16},
                new PostSubcategory { PostId=50, SubcategoryId = 22},
                new PostSubcategory { PostId=51 , SubcategoryId =19},
                new PostSubcategory { PostId=51 ,  SubcategoryId =21},
                new PostSubcategory { PostId=52, SubcategoryId =23},
                new PostSubcategory { PostId=53, SubcategoryId = 38},
                new PostSubcategory { PostId=54, SubcategoryId = 11},
                new PostSubcategory { PostId=54,  SubcategoryId =14},
                new PostSubcategory { PostId=55, SubcategoryId = 15},
                new PostSubcategory { PostId=56, SubcategoryId = 34 },
                new PostSubcategory { PostId=57, SubcategoryId = 31 },
                new PostSubcategory { PostId=58, SubcategoryId = 34},
                new PostSubcategory { PostId=58, SubcategoryId = 28},
                new PostSubcategory { PostId=59, SubcategoryId = 6},
                new PostSubcategory { PostId=60, SubcategoryId = 9},
                new PostSubcategory { PostId=61, SubcategoryId = 8},
                new PostSubcategory { PostId=62, SubcategoryId = 30 },
                new PostSubcategory { PostId=62, SubcategoryId = 29},
                new PostSubcategory { PostId=63, SubcategoryId = 16},
                new PostSubcategory { PostId=64, SubcategoryId = 22},
                new PostSubcategory { PostId=65, SubcategoryId =19},
                new PostSubcategory { PostId=65, SubcategoryId =21},
                new PostSubcategory { PostId=66, SubcategoryId =23},
                new PostSubcategory { PostId=67, SubcategoryId= 38},
                new PostSubcategory { PostId=68, SubcategoryId = 11},
                new PostSubcategory { PostId=68,  SubcategoryId =14},
                new PostSubcategory { PostId=69, SubcategoryId = 15},
                new PostSubcategory { PostId=70, SubcategoryId = 34 },
                new PostSubcategory { PostId=71, SubcategoryId = 31 },
                new PostSubcategory { PostId=72, SubcategoryId = 34},
                new PostSubcategory { PostId=72,  SubcategoryId = 28},
                new PostSubcategory { PostId=73, SubcategoryId = 6},
                new PostSubcategory { PostId=74, SubcategoryId = 9},
                new PostSubcategory { PostId=75, SubcategoryId = 8},
                new PostSubcategory { PostId=76, SubcategoryId = 30 },
                new PostSubcategory { PostId=76,  SubcategoryId = 29},
                new PostSubcategory { PostId=77, SubcategoryId = 16},
                new PostSubcategory { PostId=78, SubcategoryId = 22},
                new PostSubcategory { PostId=79, SubcategoryId =19},
                new PostSubcategory { PostId=79, SubcategoryId =21},
                new PostSubcategory { PostId=80, SubcategoryId =23},
                new PostSubcategory { PostId=81, SubcategoryId = 38},
                new PostSubcategory { PostId=82, SubcategoryId = 11},
                new PostSubcategory { PostId=82,  SubcategoryId =14},
                new PostSubcategory { PostId=83, SubcategoryId = 15},
                new PostSubcategory { PostId=84, SubcategoryId = 34 },
                new PostSubcategory { PostId=85, SubcategoryId = 31 },
                new PostSubcategory { PostId=86, SubcategoryId = 34},
                new PostSubcategory { PostId=86,  SubcategoryId = 28},
                new PostSubcategory { PostId=87, SubcategoryId = 6},
                new PostSubcategory { PostId=88 ,SubcategoryId = 9},
                new PostSubcategory { PostId=89, SubcategoryId = 8},
                new PostSubcategory { PostId=90, SubcategoryId = 30 },
                new PostSubcategory { PostId=90,  SubcategoryId = 29},
                new PostSubcategory { PostId=91, SubcategoryId = 16},
                new PostSubcategory { PostId=92, SubcategoryId = 22},
                new PostSubcategory { PostId=93, SubcategoryId =19},
                new PostSubcategory { PostId=93, SubcategoryId =21},
                new PostSubcategory { PostId=94, SubcategoryId =23},
                new PostSubcategory { PostId=95, SubcategoryId = 38},
                new PostSubcategory { PostId=96, SubcategoryId = 11},
                new PostSubcategory { PostId=96, SubcategoryId =14},
                new PostSubcategory { PostId=97, SubcategoryId = 15},
                new PostSubcategory { PostId=98, SubcategoryId = 34 },
                new PostSubcategory { PostId=99, SubcategoryId = 31 },
                new PostSubcategory { PostId=100, SubcategoryId = 34}, 
                new PostSubcategory { PostId=100 ,SubcategoryId = 28},
                new PostSubcategory { PostId=101, SubcategoryId = 6},
                new PostSubcategory { PostId=102, SubcategoryId = 9},
                new PostSubcategory { PostId=103, SubcategoryId = 8},
                new PostSubcategory { PostId=104, SubcategoryId = 30 },
                new PostSubcategory { PostId=104, SubcategoryId= 29},
                new PostSubcategory { PostId=105, SubcategoryId = 16},
                new PostSubcategory { PostId=106, SubcategoryId = 22},
                new PostSubcategory { PostId=107, SubcategoryId =19},
                new PostSubcategory { PostId=107, SubcategoryId =21},
                new PostSubcategory { PostId=108, SubcategoryId =23},
                new PostSubcategory { PostId=109, SubcategoryId = 38},
                new PostSubcategory { PostId=110, SubcategoryId = 11},
                new PostSubcategory { PostId=110,  SubcategoryId =14},
                new PostSubcategory { PostId=111, SubcategoryId = 15},
                new PostSubcategory { PostId=112, SubcategoryId = 34 }

                );
            
        }
    }
}
